articles/bot-service-channel-connect-line.md
https://github.com/MicrosoftDocs/bot-docs.ja-jp/pull/1
=> resolve conflict

articles/rest-api/bot-framework-rest-connector-api-reference.md
https://docs.microsoft.com/ja-jp/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0
=> [LOC] Back-Translation "| **アクティビティ** |"→"| **activities** |"

articles/rest-api/bot-framework-rest-direct-line-1-1-api-reference.md
https://docs.microsoft.com/ja-jp/azure/bot-service/rest-api/bot-framework-rest-direct-line-1-1-api-reference?view=azure-bot-service-4.0#get-messages
=> [LOC]Translation "Get Messages"→"メッセージの取得"

articles/bot-service-activities-entities.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-service-activities-entities?view=azure-bot-service-4.0&tabs=cs
=> [LOC] Back-Translation "ジオ"→"Geo"

articles/includes/deploy/snippet-deploy-code-to-az.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp
=> [LOC]Back-Translation "| 名前 |"→"| name |"

articles/v4sdk/abs-quickstart.md
https://docs.microsoft.com/ja-jp/azure/bot-service/abs-quickstart?view=azure-bot-service-4.0
=> Typo "| **[価格レベル]** |"→"| **価格レベル** |"

articles/bot-service-manage-channels.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-service-manage-channels?view=azure-bot-service-4.0
=> [LOC]Back-Translation "[ボット サービス]"→"[Bot Service]"

articles/v4sdk/migration/csharp-user-state-using.md
https://docs.microsoft.com/ja-jp/azure/bot-service/migration/csharp-user-state-using?view=azure-bot-service-4.0
=> [LOC]Back-Translation "[ファイル]"→"[File]"

articles/bot-service-debug-inspection-middleware.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-service-debug-inspection-middleware?view=azure-bot-service-4.0&tabs=csharp
=> [LOC]Back-Translation "[バージョン情報]"→"[About]"

articles/bot-service-debug-emulator.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-service-debug-emulator?view=azure-bot-service-4.0&tabs=csharp
=> [LOC]Back-Translation " [設定]"→"[Settings]"

articles/v4sdk/bot-builder-tutorial-dispatch.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs
=> [LOC]Back-Translation "[マイ アプリ]"→"[My Apps]"

articles/v4sdk/bot-builder-telemetry-qnamaker.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-builder-telemetry-qnamaker?view=azure-bot-service-4.0
=> [LOC] Translation "[Monitor]"→"[モニター]"

articles/rest-api/bot-framework-rest-connector-add-rich-cards.md
https://docs.microsoft.com/ja-jp/azure/bot-service/rest-api/bot-framework-rest-connector-add-rich-cards?view=azure-bot-service-4.0
=> [LOC]Back-Translation "| 型 |"→"| type |"

articles/bot-service-scenario-commerce.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-service-scenario-commerce?view=azure-bot-service-3.0
=> [LOC]Back-Translation "コグニティブ サービス"→"Cognitive Services"

articles/includes/quickstart-javascript.md
https://docs.microsoft.com/ja-jp/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0
=> [LOC]Back-Translation "[保存および接続]"→"[Save and connect]"

articles/v4sdk/bot-builder-tutorial-add-qna.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=csharp
=> Typo "https:// < >.azure.net/qnamaker"→"https://< >.azure.net/qnamaker"

articles/v4sdk/bot-builder-howto-v4-state.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=csharp
=> Showing Code "Bots/StateManagementBot.cs"

articles/bot-service-troubleshoot-500-errors.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-service-troubleshoot-500-errors?view=azure-bot-service-4.0&tabs=dotnetwebapi
=> [LOC]Back-Translation "ボット サービス"→"Bot Service"

articles/v4sdk/bot-builder-howto-qna.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-builder-howto-qna?view=azure-bot-service-4.0&tabs=js
=> [LOC]Back-Translation "**[設定]**"→"**[Settings]**"

articles/v4sdk/bot-builder-howto-v4-luis.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=csharp
=> [LOC]Back-Translation "**[管理]**"→"**[MANAGE]**"

articles/v4sdk/abs-quickstart.md
https://github.com/MicrosoftDocs/bot-docs.ja-jp/edit/live/articles/v4sdk/abs-quickstart.md
=> [LOC]Back-Translation "ボット サービスを作成する"→"Bot Service を作成する"

articles/directline-speech-bot.md
https://docs.microsoft.com/ja-jp/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0
=> Broken link "[テキスト メッセージを送受信する方法]"

articles/v4sdk/bot-builder-basics.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0&tabs=csharp
=> Typo "[**CSharp**]"→"[**C#**]"

articles/includes/deploy/snippet-additional-resources.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=csharp
=> Fixed brackets "[[App Service プラン]]"→"[App Service プラン]"

articles/v4sdk/bot-builder-basics-teams.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-builder-basics-teams?view=azure-bot-service-4.0&tabs=javascript
=> [LOC]Translation "[What are messaging extensions]"→"[メッセージングの拡張機能とは]"

articles/directline-speech-bot.md
https://docs.microsoft.com/ja-jp/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0
=> Typo "##"(H2 Tag)

articles/v4sdk/bot-builder-basics-teams.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-builder-basics-teams?view=azure-bot-service-4.0&tabs=csharp
=> [LOC]Translation "Channel created"→"チャネルの作成"

articles/v4sdk/bot-builder-basics-teams.md
https://docs.microsoft.com/ja-jp/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions
=>  [LOC]Translation "What are messaging extensions"→"メッセージングの拡張機能とは"

articles/bot-service-overview-introduction.md
https://docs.microsoft.com/ja-jp/azure/bot-service/bot-service-overview-introduction?view=azure-bot-service-4.0
=> [LOC]Fixed inappropriate japanese "展開"→"デプロイ"

articles/v4sdk/migration/javascript-user-state-using.md
https://docs.microsoft.com/ja-jp/azure/bot-service/migration/javascript-user-state-using?view=azure-bot-service-4.0
=> [LOC]Fixed inappropriate japanese "端末"→"ターミナル"

articles/javascript/bot-builder-javascript-samples.md
https://docs.microsoft.com/ja-jp/azure/bot-service/javascript/bot-builder-javascript-samples?view=azure-bot-service-4.0
=> [LOC]Fixed inappropriate japanese "複製"→"クローン"
